### PR TITLE
Add Performance category

### PR DESCRIPTION
**Pull request by jpignata**
There are classes of issues that are more precisely described as
having a potential negative performance impact. Recent examples from
engines tuning include eslint's no-extra-bind
(http://eslint.org/docs/rules/no-extra-bind) and csslint's performance
category (https://github.com/CSSLint/csslint/wiki/rules#performance).

@mrb @brynary

### CODE REVIEW

**Comment by ABaldwinHunter** [comment]
LGTM

**Comment by ABaldwinHunter** [comment]
We should update .com to accept that type of category as well.

**Comment by jpignata** [comment]
@ABaldwinHunter Thanks. I opened this up for discussion. If it's deemed worthwhile we can later figure out the right steps to integrate it.

**Comment by brynary** [comment]
:+1: on this as a category

**Comment by mrb** [comment]
:+1:

**Pull request merged**
